# Harmony Jekyll theme general configurations 

# Base URL
baseurl: /harmony

# Site live URL
#url: http://gayan.me

# Localhost 
url: http://127.0.0.1:4000  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Juana's Portfolio
  # Little description about your site
  description: Juana Isola's Portfolio.
  meta_description: > #
  Juana Isola is a creative writer and a fashion entrepreneur from Buenos Aires Argentina.
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Javier Velazquez Traut
    email: j.velazqueztraut@gmail.com
    url: http://github.com/jvelazqueztraut

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social: 
    github: gayanvirajith
    twitter: gayanvirajith
    facebook: gayanvirajith
    gplus: +GayanVirajith
    dribble: gayan
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings 
markdown: kramdown
# Using rouge instead of pygments: Page build warning from Github pages
highlighter: rouge 

# Permalinks
permalink: pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
